### ISSUE TITLE
New neo4j driver

### ISSUE THREAD

**Issue by SvenWesterlaken** [srfrnk/moneo#5]
Well, first of all thanks for this awesome plugin for mongoose.
After some digging through the code I found out this is still using the old neo4j driver.

Stating from [the github page](https://github.com/thingdom/node-neo4j) this driver isn't further developed anymore.
Besides this, most people refer to the bolt protocol being better than the original http. This bolt protocol is used in the new [neo4j-driver](https://github.com/neo4j/neo4j-javascript-driver)

Any chance we might see this implemented? Otherwise, if you don't mind, I can rewrite the code with this new driver and maybe add missed features.

**Comment by srfrnk** [comment]
Hi @SvenWesterlaken - Thanks - You can go ahead and rewrite it - that'd be great!

**Comment by SvenWesterlaken** [comment]
@srfrnk, as the [github page](https://github.com/neo4j/neo4j-javascript-driver) suggests, you should only create one driver per neo4j-database. This is why I want to implement a singleton pattern. 

However, this doesn't really fit with the current code style. For that matter, I want to ask you if you think it will still be applicable to release this as a major update (pull request) for this repo as it really changes the usage of the plugin. (besides the fact I split all functions into seperate files for readability)

If not, I would be more than happy to release it as another package on my own repo if you don't mind.

**Comment by srfrnk** [comment]
I trust your judgement in this matter more than my own.

If you think a refactoring is in order - then it is perfectly to do a major release and even add `BREAKING CHANGES` to commit is standard.

If you prefer to publish it as a new plugin - that's why I put it under open source + MIT license :)

And thanks anyway!

**Comment by SvenWesterlaken** [comment]
I will then go with a new repo, I guess. (Will need to come up with a suiting new name tho haha, for searching compatibilities).

It will give me an opportunity to learn a little bit more about releasing packages on npm (as this will be my first one) and more control to add in code coverage etc. 

Will definitely give credit to you and this repo as it really gave a foundation for me to understand the concept of these mongoose plugins :) (and the conecpt of combining it with neo4j)

If you want to, you can link my package when it finished so people can find it more easily, but I totally understand if you don't!

Peace.
